#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#Configuration de la map
def Configuration():

    Config = {'version': 'v1',
    'config': {'visState': {'filters': [],
    'layers': [{'id': '8h8bds',
        'type': 'geojson',
        'config': {'dataId': 'DATA',
        'label': 'DATA',
        'color': [246, 209, 138],
        'highlightColor': [252, 242, 26, 255],
        'columns': {'geojson': 'StreetView'},
        'isVisible': True,
        'visConfig': {'opacity': 0.8,
        'strokeOpacity': 0.8,
        'thickness': 0.5,
        'strokeColor': None,
        'colorRange': {'name': 'Global Warming',
            'type': 'sequential',
            'category': 'Uber',
            'colors': ['#5A1846',
            '#900C3F',
            '#C70039',
            '#E3611C',
            '#F1920E',
            '#FFC300']},
        'strokeColorRange': {'name': 'Global Warming',
            'type': 'sequential',
            'category': 'Uber',
            'colors': ['#5A1846',
            '#900C3F',
            '#C70039',
            '#E3611C',
            '#F1920E',
            '#FFC300']},
        'radius': 10,
        'sizeRange': [0, 10],
        'radiusRange': [0, 50],
        'heightRange': [0, 500],
        'elevationScale': 5,
        'enableElevationZoomFactor': True,
        'stroked': True,
        'filled': False,
        'enable3d': False,
        'wireframe': False},
        'hidden': False,
        'textLabel': [{'field': None,
            'color': [255, 255, 255],
            'size': 18,
            'offset': [0, 0],
            'anchor': 'start',
            'alignment': 'center'}]},
        'visualChannels': {'colorField': None,
        'colorScale': 'quantile',
        'strokeColorField': None,
        'strokeColorScale': 'quantile',
        'sizeField': None,
        'sizeScale': 'linear',
        'heightField': None,
        'heightScale': 'linear',
        'radiusField': None,
        'radiusScale': 'linear'}},
        {'id': 'k3gqmsg',
        'type': 'icon',
        'config': {'dataId': 'DATA',
        'label': 'new layer',
        'color': [137, 218, 193],
        'highlightColor': [252, 242, 26, 255],
        'columns': {'lat': 'Lat2',
        'lng': 'Long2',
        'icon': 'Icon2',
        'altitude': None},
        'isVisible': True,
        'visConfig': {'radius': 20,
        'fixedRadius': False,
        'opacity': 0.8,
        'colorRange': {'name': 'Global Warming',
            'type': 'sequential',
            'category': 'Uber',
            'colors': ['#5A1846',
            '#900C3F',
            '#C70039',
            '#E3611C',
            '#F1920E',
            '#FFC300']},
        'radiusRange': [0, 50]},
        'hidden': False,
        'textLabel': [{'field': None,
            'color': [255, 255, 255],
            'size': 18,
            'offset': [0, 0],
            'anchor': 'start',
            'alignment': 'center'}]},
        'visualChannels': {'colorField': None,
        'colorScale': 'quantile',
        'sizeField': None,
        'sizeScale': 'linear'}},
        {'id': 'u4r3kcm',
        'type': 'point',
        'config': {'dataId': 'DATA',
        'label': 'point',
        'color': [227, 26, 26],
        'highlightColor': [252, 242, 26, 255],
        'columns': {'lat': 'Latitude', 'lng': 'Longitude', 'altitude': None},
        'isVisible': True,
        'visConfig': {'radius': 11.2,
        'fixedRadius': False,
        'opacity': 0.22,
        'outline': False,
        'thickness': 2,
        'strokeColor': None,
        'colorRange': {'name': 'Global Warming',
            'type': 'sequential',
            'category': 'Uber',
            'colors': ['#5A1846',
            '#900C3F',
            '#C70039',
            '#E3611C',
            '#F1920E',
            '#FFC300']},
        'strokeColorRange': {'name': 'Global Warming',
            'type': 'sequential',
            'category': 'Uber',
            'colors': ['#5A1846',
            '#900C3F',
            '#C70039',
            '#E3611C',
            '#F1920E',
            '#FFC300']},
        'radiusRange': [0, 50],
        'filled': True},
        'hidden': False,
        'textLabel': [{'field': None,
            'color': [255, 255, 255],
            'size': 18,
            'offset': [0, 0],
            'anchor': 'start',
            'alignment': 'center'}]},
        'visualChannels': {'colorField': {'name': 'Timestamp',
        'type': 'timestamp'},
        'colorScale': 'quantile',
        'strokeColorField': None,
        'strokeColorScale': 'quantile',
        'sizeField': None,
        'sizeScale': 'linear'}}],
    'interactionConfig': {'tooltip': {'fieldsToShow': {'DATA': [{'name': 'index',
            'format': None},
        {'name': 'Unnamed: 0', 'format': None},
        {'name': 'Tripnumber', 'format': None},
        {'name': 'DriverID', 'format': None},
        {'name': 'StreetView', 'format': None},
        {'name': 'Label', 'format': None}]},
        'compareMode': False,
        'compareType': 'absolute',
        'enabled': True},
        'brush': {'size': 0.5, 'enabled': False},
        'geocoder': {'enabled': False},
        'coordinate': {'enabled': True}},
    'layerBlending': 'normal',
    'splitMaps': [],
    'animationConfig': {'currentTime': None, 'speed': 1}},
    'mapState': {'bearing': 0,
    'dragRotate': False,
    'latitude': 48.81159838019325,
    'longitude': 2.0716675049148363,
    'pitch': 0,
    'zoom': 10.552234419662668,
    'isSplit': False},
    'mapStyle': {'styleType': 'dark',
    'topLayerGroups': {},
    'visibleLayerGroups': {'label': True,
        'road': True,
        'border': False,
        'building': True,
        'water': True,
        'land': True,
        '3d building': False},
    'threeDBuildingColor': [9.665468314072013,
        17.18305478057247,
        31.1442867897876],
    'mapStyles': {}}}}

    return(Config)

